### ISSUE TITLE
Standalone full screen timer

### ISSUE THREAD

**Issue by hadley** [gadenbuie/countdown#6]
It would be really useful to have a full screen timer (i.e. with the font automatically sized to be as big as possible) without using xaringan, or other presentation format.

**Comment by gadenbuie** [comment]
Thanks for the suggestions! This should be relatively easy to work out within the package. I think I'll add a new function `countdown_fullscreen()` that wraps `countdown()` and adds a bit of additional CSS.

For my reference, this seems to achieve the desired effect:

```r
countdown(
  bottom = 0, top = 0, left = 0, right = 0, 
  padding = "0", margin = "2%", 
  font_size = "20vw"
)
```

with the additional css

```css
.countdown {
  line-height: 96vh;
}
.countdown code {
  vertical-align: middle;
}
```
